baseURL = "https://ureka.top/"
languageCode = "zh-cn"
title = "Ureka"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
mainSections = ["posts"]
description = "记录科研、技术与学习"

[params.sidebar]
compact = false
emoji = "🐟"
subtitle = "记录仿生机器人、编程与学习"

[params.article]
toc = true
readingTime = true
headingAnchor = true

[params.article.list]
showTags = true

[params.colorScheme]
toggle = true
default = "auto"

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = -100

[menu.main.params]
icon = "home"